# Linker order for every file, passed to the Metrowerks linker.

GROUP_0_FILES:=\
	$(BUILD_DIR)/asm/ctors.o\
	$(BUILD_DIR)/asm/dtors.o\

JSYSTEM:=\
	$(BUILD_DIR)/asm/JSystem/object/object-particle.o\
	$(BUILD_DIR)/asm/JSystem/JPA/control.o\
	$(BUILD_DIR)/asm/JSystem/resource.o\
	$(BUILD_DIR)/src/JSystem/data.o\
	$(BUILD_DIR)/asm/JSystem/processor.o\
	$(BUILD_DIR)/asm/JSystem/control.o\
	$(BUILD_DIR)/src/JSystem/JStudio/stb/data/stb-data-parse.o\
	$(BUILD_DIR)/asm/JSystem/functionvalue.o\
	$(BUILD_DIR)/asm/JSystem/JStudio/fvb/fvb.o\
	$(BUILD_DIR)/src/JSystem/JStudio/fvb/data/fvb-data.o\
	$(BUILD_DIR)/src/JSystem/JStudio/fvb/data/fvb-data-parse.o\
	$(BUILD_DIR)/asm/JSystem/JStudio/jstudio-control.o\
	$(BUILD_DIR)/src/JSystem/JStudio/data/jstudio-data.o\
	$(BUILD_DIR)/asm/JSystem/JStudio/jstudio-object.o\
	$(BUILD_DIR)/asm/JSystem/object/object-id.o\
	$(BUILD_DIR)/asm/JSystem/JStudio/stb/stb.o\
	$(BUILD_DIR)/src/JSystem/JStudio/stb/data/stb-data.o\
	$(BUILD_DIR)/asm/JSystem/JStudio/jstudio-math.o\
	$(BUILD_DIR)/asm/JSystem/object/object-light.o\
	$(BUILD_DIR)/asm/JSystem/object/object.o\
	$(BUILD_DIR)/asm/JSystem/object/object-actor.o\
	$(BUILD_DIR)/src/JSystem/object/object-ambientlight.o\
	$(BUILD_DIR)/asm/JSystem/object/object-camera.o\
	$(BUILD_DIR)/src/JSystem/object/object-fog.o\
	$(BUILD_DIR)/asm/JSystem/JSG/control.o\
	$(BUILD_DIR)/src/JSystem/object/object-message.o\
	$(BUILD_DIR)/asm/JSystem/object/control.o\
	$(BUILD_DIR)/asm/JSystem/object/object-sound.o\
	$(BUILD_DIR)/asm/JSystem/JAI/control.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DUDL.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DUMotion.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DUShadow.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DUMtxCache.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRAram.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRAramArchive.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRAramBlock.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRAramHeap.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRAramPiece.o\
	$(BUILD_DIR)/src/JSystem/JKR/JKRAramStream.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRArchivePri.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRArchivePub.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRCompArchive.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRDecomp.o\
	$(BUILD_DIR)/src/JSystem/JKR/JKRDisposer.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRDvdFile.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRDvdAramRipper.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRDvdArchive.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRDvdRipper.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRExpHeap.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRFileCache.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRFileFinder.o\
	$(BUILD_DIR)/src/JSystem/JKR/JKRFile.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRFileLoader.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRHeap.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRMemArchive.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRSolidHeap.o\
	$(BUILD_DIR)/asm/JSystem/JKR/JKRThread.o\
	$(BUILD_DIR)/src/JSystem/JSupport/JSUOutputStream.o\
	$(BUILD_DIR)/src/JSystem/JSupport/JSUInputStream.o\
	$(BUILD_DIR)/src/JSystem/JSupport/JSUList.o\
	$(BUILD_DIR)/src/JSystem/JSupport/JSUMemoryStream.o\
	$(BUILD_DIR)/src/JSystem/JSupport/JSUFileStream.o\
	$(BUILD_DIR)/asm/JSystem/binary.o\
	$(BUILD_DIR)/asm/JSystem/linklist.o\
	$(BUILD_DIR)/asm/JSystem/std/std-list.o\
	$(BUILD_DIR)/asm/JSystem/std/std-vector.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTAssert.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTConsole.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTDbPrint.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTDirectFile.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTDirectPrint.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTException.o\
	$(BUILD_DIR)/src/JSystem/JUT/JUTFader.o\
	$(BUILD_DIR)/src/JSystem/JUT/JUTFont.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTGamePad.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTGraphFifo.o\
	$(BUILD_DIR)/src/JSystem/JUT/JUTNameTab.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTPalette.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTProcBar.o\
	$(BUILD_DIR)/src/JSystem/JUT/JUTResFont.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTResource.o\
	$(BUILD_DIR)/src/JSystem/JUT/JUTRomFont.o\
	$(BUILD_DIR)/src/JSystem/JUT/JUTFontData_Ascfont_fix12.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTTexture.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTVideo.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTXfb.o\
	$(BUILD_DIR)/asm/JSystem/JUT/JUTCacheFont.o\
	$(BUILD_DIR)/asm/JSystem/JMath/JMath.o\
	$(BUILD_DIR)/src/JSystem/JMath/random.o\
	$(BUILD_DIR)/asm/JSystem/JMath/JMATrigonometric.o\
	$(BUILD_DIR)/src/JSystem/J2D/J2DOrthoGraph.o\
	$(BUILD_DIR)/src/JSystem/J2D/J2DPerspGraph.o\
	$(BUILD_DIR)/src/JSystem/J2D/J2DGrafContext.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DPane.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DPicture.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DPrint.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DScreen.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DTextBox.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DWindow.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DWindowEx.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DAnmLoader.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DBloSaver.o\
	$(BUILD_DIR)/src/JSystem/J2D/J2DManage.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DMatBlock.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DMaterial.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DMaterialFactory.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DPictureEx.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DTevs.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DTextBoxEx.o\
	$(BUILD_DIR)/asm/JSystem/J2D/J2DAnimation.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DSys.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DVertex.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DTransform.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DPacket.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DShape.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DMaterial.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DTevs.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DDrawBuffer.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DModel.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DAnimation.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DMaterialAnm.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DCluster.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DJoint.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DMaterialFactory.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DBinaryFormat.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DModelLoader.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DJointFactory.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DShapeFactory.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DAnmLoader.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DModelSaver.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DGD.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DMatBlock.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DModelData.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DMaterialAttach.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DMaterialFactory_v21.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DShapeMtx.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DModelLoaderCalcSize.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DJointTree.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DSkinDeform.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DShapeDraw.o\
	$(BUILD_DIR)/asm/JSystem/J3D/J3DMtxBuffer.o\
	$(BUILD_DIR)/src/JSystem/J3D/J3DShapeTable.o\
	$(BUILD_DIR)/asm/JSystem/JFW/JFWSystem.o\
	$(BUILD_DIR)/asm/JSystem/JFW/JFWDisplay.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPABaseShape.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAChildShape.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPADynamicsBlock.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAEmitter.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAEmitterManager.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAExTexShape.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAExtraShape.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAFieldBlock.o\
	$(BUILD_DIR)/src/JSystem/JPA/JPAKeyBlock.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAMath.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAParticle.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAResource.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAResourceLoader.o\
	$(BUILD_DIR)/asm/JSystem/JPA/JPAResourceManager.o\
	$(BUILD_DIR)/src/JSystem/JPA/JPATexture.o\
	$(BUILD_DIR)/src/JSystem/JSG/JSGSystem.o\
	$(BUILD_DIR)/src/JSystem/JSG/JSGCamera.o\
	$(BUILD_DIR)/src/JSystem/JSG/JSGObject.o\
	$(BUILD_DIR)/src/JSystem/JSG/JSGActor.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASWSParser.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASBankMgr.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASBasicBank.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASBasicInst.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASBasicWaveBank.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASBNKParser.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASDrumSet.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASInstEffect.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASInstRand.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASInstSense.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASSimpleWaveBank.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASWaveArcLoader.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASWaveBank.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASWaveBankMgr.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASBank.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASTrackPort.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASOuterParam.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASPlayer_impl.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASRegisterParam.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASSeqCtrl.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASSeqParser.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASTrack.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASTrackInterrupt.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASOscillator.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASChannel.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASDriverIF.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASDSPChannel.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASDSPInterface.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASAudioThread.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASCalc.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASCallback.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASCmdStack.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASDvdThread.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASHeapCtrl.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASProbe.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASResArcLoader.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASReport.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASAiCtrl.o\
	$(BUILD_DIR)/src/JSystem/JAS/JASChannelUpdater.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASTaskThread.o\
	$(BUILD_DIR)/asm/JSystem/JAS/JASAramStream.o\
	$(BUILD_DIR)/asm/JSystem/dsp/dspproc.o\
	$(BUILD_DIR)/asm/JSystem/dsp/dsptask.o\
	$(BUILD_DIR)/asm/JSystem/dsp/osdsp.o\
	$(BUILD_DIR)/asm/JSystem/dsp/osdsp_task.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIAnimation.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIBankWave.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIBasic.o\
	$(BUILD_DIR)/src/JSystem/JAI/JAIConst.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIDummyObject.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIFx.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIGlobalParameter.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIInitData.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAISeMgr.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAISequenceHeap.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAISequenceMgr.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAISound.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAISoundTable.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIStreamMgr.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAISystemInterface.o\
	$(BUILD_DIR)/asm/JSystem/JAI/JAIObject.o\
	$(BUILD_DIR)/src/JSystem/JAD/JADHioNode.o\
	$(BUILD_DIR)/asm/JSystem/JAL/JALCalc.o\
	$(BUILD_DIR)/asm/JSystem/JAU/JAUData.o\
	$(BUILD_DIR)/asm/JSystem/JAU/JAUDataMgr.o\

DOLPHIN:=\
	$(BUILD_DIR)/src/Dolphin/mainloop.o\
	$(BUILD_DIR)/src/Dolphin/nubevent.o\
	$(BUILD_DIR)/src/Dolphin/nubinit.o\
	$(BUILD_DIR)/src/Dolphin/msg.o\
	$(BUILD_DIR)/asm/Dolphin/msgbuf.o\
	$(BUILD_DIR)/asm/Dolphin/serpoll.o\
	$(BUILD_DIR)/src/Dolphin/usr_put.o\
	$(BUILD_DIR)/src/Dolphin/dispatch.o\
	$(BUILD_DIR)/asm/Dolphin/msghndlr.o\
	$(BUILD_DIR)/asm/Dolphin/support.o\
	$(BUILD_DIR)/src/Dolphin/mutex_TRK.o\
	$(BUILD_DIR)/src/Dolphin/notify.o\
	$(BUILD_DIR)/src/Dolphin/flush_cache.o\
	$(BUILD_DIR)/src/Dolphin/mem_TRK.o\
	$(BUILD_DIR)/asm/Dolphin/targimpl.o\
	$(BUILD_DIR)/src/Dolphin/targsupp.o\
	$(BUILD_DIR)/asm/Dolphin/mpc_7xx_603e.o\
	$(BUILD_DIR)/asm/Dolphin/__exception.o\
	$(BUILD_DIR)/asm/Dolphin/dolphin_trk.o\
	$(BUILD_DIR)/src/Dolphin/main_TRK.o\
	$(BUILD_DIR)/asm/Dolphin/dolphin_trk_glue.o\
	$(BUILD_DIR)/src/Dolphin/targcont.o\
	$(BUILD_DIR)/src/Dolphin/target_options.o\
	$(BUILD_DIR)/asm/Dolphin/mslsupp.o\
	$(BUILD_DIR)/src/Dolphin/UDP_Stubs.o\
	$(BUILD_DIR)/src/Dolphin/ddh/main.o\
	$(BUILD_DIR)/asm/Dolphin/CircleBuffer.o\
	$(BUILD_DIR)/src/Dolphin/main.o\
	$(BUILD_DIR)/src/Dolphin/MWTrace.o\
	$(BUILD_DIR)/src/Dolphin/MWCriticalSection_gc.o\
	$(BUILD_DIR)/src/Dolphin/__va_arg.o\
	$(BUILD_DIR)/asm/Dolphin/global_destructor_chain.o\
	$(BUILD_DIR)/src/Dolphin/CPlusLibPPC.o\
	$(BUILD_DIR)/asm/Dolphin/NMWException.o\
	$(BUILD_DIR)/src/Dolphin/ptmf.o\
	$(BUILD_DIR)/asm/Dolphin/runtime.o\
	$(BUILD_DIR)/asm/Dolphin/__init_cpp_exceptions.o\
	$(BUILD_DIR)/asm/Dolphin/Gecko_ExceptionPPC.o\
	$(BUILD_DIR)/src/Dolphin/GCN_mem_alloc.o\
	$(BUILD_DIR)/src/Dolphin/abort_exit.o\
	$(BUILD_DIR)/asm/Dolphin/alloc.o\
	$(BUILD_DIR)/src/Dolphin/ansi_files.o\
	$(BUILD_DIR)/asm/Dolphin/ansi_fp.o\
	$(BUILD_DIR)/src/Dolphin/arith.o\
	$(BUILD_DIR)/src/Dolphin/buffer_io.o\
	$(BUILD_DIR)/src/Dolphin/critical_regions.gamecube.o\
	$(BUILD_DIR)/src/Dolphin/ctype.o\
	$(BUILD_DIR)/asm/Dolphin/direct_io.o\
	$(BUILD_DIR)/src/Dolphin/errno.o\
	$(BUILD_DIR)/src/Dolphin/file_io.o\
	$(BUILD_DIR)/src/Dolphin/FILE_POS.o\
	$(BUILD_DIR)/src/Dolphin/locale.o\
	$(BUILD_DIR)/src/Dolphin/mbstring.o\
	$(BUILD_DIR)/src/Dolphin/mem.o\
	$(BUILD_DIR)/asm/Dolphin/mem_funcs.o\
	$(BUILD_DIR)/src/Dolphin/misc_io.o\
	$(BUILD_DIR)/asm/Dolphin/printf.o\
	$(BUILD_DIR)/src/Dolphin/rand.o\
	$(BUILD_DIR)/src/Dolphin/float.o\
	$(BUILD_DIR)/asm/Dolphin/scanf.o\
	$(BUILD_DIR)/src/Dolphin/string.o\
	$(BUILD_DIR)/asm/Dolphin/strtold.o\
	$(BUILD_DIR)/asm/Dolphin/strtoul.o\
	$(BUILD_DIR)/src/Dolphin/wchar_io.o\
	$(BUILD_DIR)/src/Dolphin/uart_console_io_gcn.o\
	$(BUILD_DIR)/src/Dolphin/e_asin.o\
	$(BUILD_DIR)/src/Dolphin/e_atan2.o\
	$(BUILD_DIR)/src/Dolphin/e_exp.o\
	$(BUILD_DIR)/src/Dolphin/e_fmod.o\
	$(BUILD_DIR)/src/Dolphin/e_log.o\
	$(BUILD_DIR)/src/Dolphin/e_log10.o\
	$(BUILD_DIR)/src/Dolphin/e_pow.o\
	$(BUILD_DIR)/src/Dolphin/e_rem_pio2.o\
	$(BUILD_DIR)/src/Dolphin/k_cos.o\
	$(BUILD_DIR)/src/Dolphin/k_rem_pio2.o\
	$(BUILD_DIR)/src/Dolphin/k_sin.o\
	$(BUILD_DIR)/src/Dolphin/k_tan.o\
	$(BUILD_DIR)/src/Dolphin/s_atan.o\
	$(BUILD_DIR)/src/Dolphin/s_ceil.o\
	$(BUILD_DIR)/src/Dolphin/s_copysign.o\
	$(BUILD_DIR)/src/Dolphin/s_cos.o\
	$(BUILD_DIR)/src/Dolphin/s_floor.o\
	$(BUILD_DIR)/src/Dolphin/s_frexp.o\
	$(BUILD_DIR)/src/Dolphin/s_ldexp.o\
	$(BUILD_DIR)/src/Dolphin/s_modf.o\
	$(BUILD_DIR)/src/Dolphin/s_sin.o\
	$(BUILD_DIR)/src/Dolphin/s_tan.o\
	$(BUILD_DIR)/src/Dolphin/w_asin.o\
	$(BUILD_DIR)/src/Dolphin/w_atan2.o\
	$(BUILD_DIR)/src/Dolphin/w_exp.o\
	$(BUILD_DIR)/src/Dolphin/w_fmod.o\
	$(BUILD_DIR)/src/Dolphin/w_log10.o\
	$(BUILD_DIR)/src/Dolphin/w_pow.o\
	$(BUILD_DIR)/src/Dolphin/e_sqrt.o\
	$(BUILD_DIR)/src/Dolphin/math_ppc.o\
	$(BUILD_DIR)/src/Dolphin/w_sqrt.o\
	$(BUILD_DIR)/src/Dolphin/extras.o\
	$(BUILD_DIR)/src/Dolphin/DebuggerDriver.o\
	$(BUILD_DIR)/asm/Dolphin/DebuggerDriver.o\
	$(BUILD_DIR)/asm/Dolphin/vi.o\
	$(BUILD_DIR)/src/Dolphin/AmcExi2Stubs.o\
	$(BUILD_DIR)/asm/Dolphin/ar.o\
	$(BUILD_DIR)/asm/Dolphin/arq.o\
	$(BUILD_DIR)/src/Dolphin/PPCArch.o\
	$(BUILD_DIR)/asm/Dolphin/CARDBios.o\
	$(BUILD_DIR)/asm/Dolphin/CARDUnlock.o\
	$(BUILD_DIR)/asm/Dolphin/CARDRdwr.o\
	$(BUILD_DIR)/asm/Dolphin/CARDBlock.o\
	$(BUILD_DIR)/asm/Dolphin/CARDDir.o\
	$(BUILD_DIR)/asm/Dolphin/CARDCheck.o\
	$(BUILD_DIR)/asm/Dolphin/CARDMount.o\
	$(BUILD_DIR)/asm/Dolphin/CARDFormat.o\
	$(BUILD_DIR)/asm/Dolphin/CARDOpen.o\
	$(BUILD_DIR)/asm/Dolphin/CARDCreate.o\
	$(BUILD_DIR)/asm/Dolphin/CARDRead.o\
	$(BUILD_DIR)/asm/Dolphin/CARDWrite.o\
	$(BUILD_DIR)/asm/Dolphin/CARDStat.o\
	$(BUILD_DIR)/asm/Dolphin/CARDNet.o\
	$(BUILD_DIR)/src/Dolphin/db.o\
	$(BUILD_DIR)/asm/Dolphin/dsp.o\
	$(BUILD_DIR)/src/Dolphin/dsp_debug.o\
	$(BUILD_DIR)/asm/Dolphin/dsp_task.o\
	$(BUILD_DIR)/asm/Dolphin/dvdlow.o\
	$(BUILD_DIR)/asm/Dolphin/dvdfs.o\
	$(BUILD_DIR)/asm/Dolphin/dvd.o\
	$(BUILD_DIR)/src/Dolphin/dvdqueue.o\
	$(BUILD_DIR)/src/Dolphin/dvderror.o\
	$(BUILD_DIR)/src/Dolphin/dvdidutils.o\
	$(BUILD_DIR)/src/Dolphin/dvdFatal.o\
	$(BUILD_DIR)/src/Dolphin/fstload.o\
	$(BUILD_DIR)/asm/Dolphin/EXIBios.o\
	$(BUILD_DIR)/asm/Dolphin/EXIUart.o\
	$(BUILD_DIR)/src/Dolphin/GDBase.o\
	$(BUILD_DIR)/asm/Dolphin/GDGeometry.o\
	$(BUILD_DIR)/asm/Dolphin/GXInit.o\
	$(BUILD_DIR)/asm/Dolphin/GXFifo.o\
	$(BUILD_DIR)/asm/Dolphin/GXAttr.o\
	$(BUILD_DIR)/asm/Dolphin/GXMisc.o\
	$(BUILD_DIR)/asm/Dolphin/GXGeometry.o\
	$(BUILD_DIR)/asm/Dolphin/GXFrameBuf.o\
	$(BUILD_DIR)/asm/Dolphin/GXLight.o\
	$(BUILD_DIR)/asm/Dolphin/GXTexture.o\
	$(BUILD_DIR)/src/Dolphin/GXBump.o\
	$(BUILD_DIR)/asm/Dolphin/GXTev.o\
	$(BUILD_DIR)/asm/Dolphin/GXPixel.o\
	$(BUILD_DIR)/asm/Dolphin/GXDisplayList.o\
	$(BUILD_DIR)/asm/Dolphin/GXTransform.o\
	$(BUILD_DIR)/asm/Dolphin/GXPerf.o\
	$(BUILD_DIR)/asm/Dolphin/mtx.o\
	$(BUILD_DIR)/asm/Dolphin/mtxvec.o\
	$(BUILD_DIR)/asm/Dolphin/mtx44.o\
	$(BUILD_DIR)/src/Dolphin/vec.o\
	$(BUILD_DIR)/src/Dolphin/odenotstub.o\
	$(BUILD_DIR)/src/Dolphin/OS.o\
	$(BUILD_DIR)/asm/Dolphin/OSAlarm.o\
	$(BUILD_DIR)/src/Dolphin/OSAlloc.o\
	$(BUILD_DIR)/src/Dolphin/OSArena.o\
	$(BUILD_DIR)/src/Dolphin/OSAudioSystem.o\
	$(BUILD_DIR)/src/Dolphin/OSCache.o\
	$(BUILD_DIR)/asm/Dolphin/OSContext.o\
	$(BUILD_DIR)/asm/Dolphin/OSError.o\
	$(BUILD_DIR)/asm/Dolphin/OSFont.o\
	$(BUILD_DIR)/asm/Dolphin/OSInterrupt.o\
	$(BUILD_DIR)/src/Dolphin/OSLink.o\
	$(BUILD_DIR)/src/Dolphin/OSMessage.o\
	$(BUILD_DIR)/asm/Dolphin/OSMemory.o\
	$(BUILD_DIR)/asm/Dolphin/OSMutex.o\
	$(BUILD_DIR)/asm/Dolphin/OSReboot.o\
	$(BUILD_DIR)/asm/Dolphin/OSReset.o\
	$(BUILD_DIR)/asm/Dolphin/OSResetSW.o\
	$(BUILD_DIR)/asm/Dolphin/OSRtc.o\
	$(BUILD_DIR)/src/Dolphin/OSSync.o\
	$(BUILD_DIR)/asm/Dolphin/OSThread.o\
	$(BUILD_DIR)/asm/Dolphin/OSTime.o\
	$(BUILD_DIR)/asm/Dolphin/__mem.o\
	$(BUILD_DIR)/src/Dolphin/__start.o\
	$(BUILD_DIR)/src/Dolphin/__ppc_eabi_init.o\
	$(BUILD_DIR)/asm/Dolphin/Padclamp.o\
	$(BUILD_DIR)/asm/Dolphin/Pad.o\
	$(BUILD_DIR)/asm/Dolphin/SIBios.o\
	$(BUILD_DIR)/src/Dolphin/SISamplingRate.o\
	$(BUILD_DIR)/asm/Dolphin/ai.o\
	$(BUILD_DIR)/asm/Dolphin/THPDec.o\
	$(BUILD_DIR)/asm/Dolphin/THPAudio.o\
	$(BUILD_DIR)/src/Dolphin/GBA.o\
	$(BUILD_DIR)/src/Dolphin/GBARead.o\
	$(BUILD_DIR)/src/Dolphin/GBAWrite.o\
	$(BUILD_DIR)/asm/Dolphin/GBAXfer.o

YAMASHITA:=\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/enemyBase.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/pelplant.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/pelplantState.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyInteractBattle.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/generalEnemyMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/kochappyAnimator.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/kochappy.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/kochappyState.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/kochappyMgr.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/enemyAction.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/chappy.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/chappyState.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/chappyAnimator.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/chappyMgr.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/lifeGaugeMgr.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/carryInfoMgr.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/gameLightMgr.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/vtxAnm.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyInfo.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/farm.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/farmMgr.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/genEnemy.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/timeMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/pelplantGenerator.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyInteractActions.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyAnimatorBase.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/enemyStoneMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyStoenInfo.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/enemyStoneDrawInfo.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyStoneObj.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyParmsBase.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/walkSmokeEffect.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/ChappyBaseMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/ChappyBase.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/BlueChappyMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/BlueChappy.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/YellowChappyMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/YellowChappy.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/BlueKochappyMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/BlueKochappy.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/YellowKochappy.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/YellowKochappyMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/KochappyBaseMgr.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/KochappyBase.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyBlendAnimatorBase.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyPelletInfo.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyEffectNode.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyMgrBase.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/enemyFSM.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/singleGS_ZukanParms.o\
	$(BUILD_DIR)/src/plugProjectYamashitaU/treasureLightMgr.o\
	$(BUILD_DIR)/asm/plugProjectYamashitaU/effectAnimator.o\

KANDO:=\
	$(BUILD_DIR)/src/plugProjectKandoU/pikiAnimator.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/collinfo.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameDynamics.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/creature.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/fakePiki.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/navi.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/piki.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/baseGameSection.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGameSection.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/cellPyramid.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/naviMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pikiMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/mapMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/baseHIOSection.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/naviWhistle.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pelletMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/routeMgr.o\
	$(BUILD_DIR)/src/plugProjectKandoU/onyonMgr.o\
	$(BUILD_DIR)/src/plugProjectKandoU/objectTypes.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/naviState.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pikiState.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/interactPiki.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameCPlate.o\
	$(BUILD_DIR)/src/plugProjectKandoU/updateMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiAction.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiPrimitives.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiFormation.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/creatureStick.o\
	$(BUILD_DIR)/src/plugProjectKandoU/interactBattle.o\
	$(BUILD_DIR)/src/plugProjectKandoU/aiFree.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiAttack.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiTransport.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiEnter.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pathfinder.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pelletState.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/dynCreature.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameGenerator.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/genPiki.o\
	$(BUILD_DIR)/src/plugProjectKandoU/genNavi.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/genItem.o\
	$(BUILD_DIR)/src/plugProjectKandoU/gameStages.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameSeaMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pikiAI.o\
	$(BUILD_DIR)/src/plugProjectKandoU/pelletConfig.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameFootmark.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameSystem.o\
	$(BUILD_DIR)/src/plugProjectKandoU/aiConstants.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameMapParts.o\
	$(BUILD_DIR)/src/plugProjectKandoU/vsGameSection.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gamePlatMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemGate.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiBreakGate.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameStat.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemHole.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemHoney.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameCaveInfo.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/creatureLOD.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/interactNavi.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemPikihead.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemPlant.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemRock.o\
	$(BUILD_DIR)/src/plugProjectKandoU/aiBreakRock.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiCrop.o\
	$(BUILD_DIR)/src/plugProjectKandoU/registItem.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gamePlayData.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemCave.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemBigFountain.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemBridge.o\
	$(BUILD_DIR)/src/plugProjectKandoU/pikiContainer.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameGeneratorCache.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemTreasure.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemDownFloor.o\
	$(BUILD_DIR)/src/plugProjectKandoU/kandoLib.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemBarrel.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pelletNumber.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pelletCarcass.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pelletFruit.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pelletOtakara.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/genPellet.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/pelletItem.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/mapMgrTraceMove.o\
	$(BUILD_DIR)/src/plugProjectKandoU/efxModelObjects.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemUjamushi.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiWeed.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/flockMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/itemWeed.o\
	$(BUILD_DIR)/src/plugProjectKandoU/aiBridge.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiTeki.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_MainGame.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_CaveGame.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_MainResult.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_CaveResult.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_WorldMap.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_FileSelect.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gamePlayDataMemCard.o\
	$(BUILD_DIR)/src/plugProjectKandoU/baseHIOparms.o\
	$(BUILD_DIR)/src/plugProjectKandoU/radarInfo.o\
	$(BUILD_DIR)/src/plugProjectKandoU/singleGS_Movie.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/navi_demoCheck.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_Zukan.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameResultTexMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gamePelletList.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/vsGS_Title.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/vsGS_Game.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/vsGS_Result.o\
	$(BUILD_DIR)/src/plugProjectKandoU/vsGS_Load.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/vsStageData.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/cellMgrParms.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/cellIterator.o\
	$(BUILD_DIR)/src/plugProjectKandoU/vsGS_VSGame.o\
	$(BUILD_DIR)/src/plugProjectKandoU/gameSoundEvent.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiBattle.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameDeathCount.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiBore.o\
	$(BUILD_DIR)/src/plugProjectKandoU/mapPartsView.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_Ending.o\
	$(BUILD_DIR)/src/plugProjectKandoU/gameIconTexture.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gameTekiStat.o\
	$(BUILD_DIR)/src/plugProjectKandoU/gameHighscore.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/gamePlayCommonData.o\
	$(BUILD_DIR)/src/plugProjectKandoU/pelletCarry.o\
	$(BUILD_DIR)/src/plugProjectKandoU/gameChallenge2D.o\
	$(BUILD_DIR)/src/plugProjectKandoU/vsTekiMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/vsCardMgr.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/aiRescue.o\
	$(BUILD_DIR)/src/plugProjectKandoU/baseGameSectionDraw.o\
	$(BUILD_DIR)/src/plugProjectKandoU/singleGS_Load.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/singleGS_DayEnd.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/baseGameSectionKantei.o\
	$(BUILD_DIR)/src/plugProjectKandoU/sweepPrune.o\
	$(BUILD_DIR)/asm/plugProjectKandoU/texCaster.o\
	$(BUILD_DIR)/src/plugProjectKandoU/vsCoinOtakaraName.o\
	$(BUILD_DIR)/src/plugProjectKandoU/pelletBirthBuffer.o\
	$(BUILD_DIR)/src/plugProjectKandoU/vsFifo.o\

NISHIMURA:=\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/nslibmath.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/ShadowCylinder.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/playCamera.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/shadowMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MapUnit.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/MapNode.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/EnemyUnit.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/RandMapMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RandMapDraw.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RandMapChecker.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/RandMapUnit.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/RandEnemyUnit.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/DoorNode.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MapUnitGenerator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MapCreator.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/RandMapScore.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ItemUnit.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/RandItemUnit.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GateUnit.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RandGateUnit.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ObjectLayout.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/CameraMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/ContRumble.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/RumbleMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/PomAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/PomMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Pom.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/PomState.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/FrogState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FrogAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FrogMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Frog.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/UjibMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Ujib.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/UjibState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/UjibAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KoganeState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KoganeMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Kogane.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KoganeAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/QurioneState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/QurioneMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Qurione.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/QurioneAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RumbleData.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MaroFrogMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/MaroFrog.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RockState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RockAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RockMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Rock.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/UjiaState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/UjiaAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/UjiaMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Ujia.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/TobiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/TobiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/TobiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Tobi.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HibaState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HibaAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HibaMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Hiba.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GasHibaState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GasHibaAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GasHibaMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GasHiba.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ElecHibaState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ElecHibaAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ElecHibaMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/ElecHiba.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SaraiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SaraiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SaraiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Sarai.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/TankState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/TankAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/TankMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Tank.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/CatfishMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Catfish.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/TadpoleState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/TadpoleAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/TadpoleMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Tadpole.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/ElecBugState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ElecBugAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ElecBugMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/ElecBug.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/WtankMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Wtank.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ArmorMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Armor.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Mar.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MarAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MarMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/MarState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/WealthyMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Wealthy.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FartMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Fart.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/ArmorState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ArmorAnimator.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/QueenState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/QueenAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/QueenMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Queen.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BabyState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BabyAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BabyMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Baby.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/DemonMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Demon.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/QueenShadow.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FireChappyMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FireChappy.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SnakeCrowState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SnakeCrowAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SnakeCrowMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SnakeCrow.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/KumaChappyState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KumaChappyAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KumaChappyMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/KumaChappy.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/FuefukiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FuefukiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FuefukiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Fuefuki.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KoganemushiMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Koganemushi.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FtankMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/Ftank.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RandPlantUnit.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/HanachirashiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HanachirashiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HanachirashiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Hanachirashi.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/DamagumoState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/DamagumoAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/DamagumoMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Damagumo.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/IKSystemMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/IKSystemBase.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/DamagumoShadow.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KurageState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KurageAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KurageMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Kurage.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BombSaraiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BombSaraiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BombSaraiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BombSarai.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/OtakaraBaseState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/OtakaraBaseAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/OtakaraBaseMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/OtakaraBase.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FireOtakaraMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FireOtakara.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/WaterOtakaraMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/WaterOtakara.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GasOtakaraMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GasOtakara.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ElecOtakaraMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ElecOtakara.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/ImomushiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ImomushiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/ImomushiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Imomushi.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HoudaiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HoudaiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HoudaiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/HoudaiShadow.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Houdai.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/HoudaiShotGun.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/LeafChappyMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/LeafChappy.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BigFootState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BigFootAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BigFootMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BigFootShadow.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BigFoot.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SnakeWholeState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SnakeWholeAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SnakeWholeMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SnakeWhole.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SnakeJointMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/OniKurageState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/OniKurageAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/OniKurageMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/OniKurage.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BigTreasureState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BigTreasureMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BigTreasureShadow.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BigTreasure.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/KabutoState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KabutoAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KabutoMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Kabuto.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/KumaKochappyState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KumaKochappyAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/KumaKochappyMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/KumaKochappy.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/MiniHoudaiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MiniHoudaiAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/MiniHoudaiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/MiniHoudai.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/MiniHoudaiShotGun.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SokkuriState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SokkuriAnimator.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/SokkuriMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Sokkuri.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/JointShadowBase.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/UmimushiShadow.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/HanaMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/Hana.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/BigTreasureAttack.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SnakeCrowShadow.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/SnakeWholeShadow.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BombOtakaraMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/BombOtakara.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/DangoMushiState.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/DangoMushiMgr.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/DangoMushi.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GreenKabutoMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/GreenKabuto.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RedKabutoMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RedKabuto.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FixKabutoMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FixKabuto.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/RandCapEnemyUnit.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/NormMiniHoudaiMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/NormMiniHoudai.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FixMiniHoudaiMgr.o\
	$(BUILD_DIR)/src/plugProjectNishimuraU/FixMiniHoudai.o\
	$(BUILD_DIR)/asm/plugProjectNishimuraU/TyreShadow.o\

OGAWA:=\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogScreen.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogDopingScreen.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogPikminCounter.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogAnime.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogCounter.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogLifeGauge.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSunMeter.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogCatchPiki.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogContenaCounter.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogMapCounter.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogAnimTextScreen.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogCallBackMessage.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogMenuMgr.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogCallBackScreen.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogCounterRV.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogSE.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogCounterDay.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/testScene.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/testObj.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogSceneGround.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjGround.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogCopyPane.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogBloGroup.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/DispMemberBase.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogLib2D.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSMenuMap.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSMenuMap.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSMenuItem.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSMenuItem.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSMenuPause.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSMenuPause.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSMenuBase.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjCourseName.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogUtil.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogSceneCourseName.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjKantei.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneKantei.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSpecialItem.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSpecialItem.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjFloor.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneFloor.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjCave.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneCave.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjAnaDemo.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneAnaDemo.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjChallenge2P.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneChallenge2P.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjContena.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneContena.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSMenuPauseDoukutu.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSMenuPauseDoukutu.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogObjUfo.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneUfo.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSave.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSave.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjFinalMsg.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneFinalMsg.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjVs.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneVs.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjChallenge1P.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneChallenge1P.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogScaleMgr.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSMenuPauseVs.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSMenuPauseVs.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogFuriko.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogCounterSlot.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjWorldMapInfoWindow0.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneWorldMapInfoWindow0.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjWorldMapInfoWindow1.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneWorldMapInfoWindow1.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogTotalPokoScreen.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjChallengeBase.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneChallengeBase.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogCallBackPicture.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogDrawAfter.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogOtakaraSensor.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogTitleMsg.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogAngleMgr.o\
	$(BUILD_DIR)/src/plugProjectOgawaU/ogSceneSMenuCont.o\
	$(BUILD_DIR)/asm/plugProjectOgawaU/ogObjSMenuCont.o\

HIKINO:=\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSSeq.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSGame.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSSystemIF.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSAutoBgm.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSBnkMgr.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSTaskBase.o\
	$(BUILD_DIR)/src/plugProjectHikinoU/PSBgmTask.o\
	$(BUILD_DIR)/src/plugProjectHikinoU/PSCreatureMgr.o\
	$(BUILD_DIR)/src/plugProjectHikinoU/PSAutoBgm_MeloArranger.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSSe.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSSeBase.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSScene.o\
	$(BUILD_DIR)/src/plugProjectHikinoU/PSBgmTrack.o\
	$(BUILD_DIR)/asm/plugProjectHikinoU/PSDirector.o\

MORIMURA:=\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/dayEndCount.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/hurryUp2D.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/gameOver2D.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/testBase.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/bombState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/bombAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/bombMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/bomb.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/eggState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/eggAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/eggMgr.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/egg.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/panModokiState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/panModokiAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/panModokiMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/panModoki.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/plantsMgr.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/plantsAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/plants.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/kingChappyState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/kingChappyMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/kingChappy.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/miulinState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/miulinAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/miulinMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/miulin.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/jigumoState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/jigumoAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/jigumoMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/jigumo.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/enemyNestMgr.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/enemyNest.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/tamagoMushiState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/tamagoMushiAnimator.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/tamagoMushiMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/tamagoMushi.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/zukan2D.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/hiScore2D.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/umiMushiState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/umiMushiAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/umiMushiMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/umiMushi.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/shijimiChouState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/shijimiChouAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/shijimiChouMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/shijimiChou.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/challengeSelect2D.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/challengeResult2D.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/vsSelect2D.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/mrUtil.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/scrollList.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/mrWindow.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/blackManState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/blackManAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/blackManMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/blackMan.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/tyreState.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/tyreAnimator.o\
	$(BUILD_DIR)/src/plugProjectMorimuraU/tyreMgr.o\
	$(BUILD_DIR)/asm/plugProjectMorimuraU/tyre.o\

EBISAWA:=\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efxBase.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efxEnemy.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efxObject.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efxPikmin.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/particle2dMgr.o\
	$(BUILD_DIR)/src/plugProjectEbisawaU/efx2dBase.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efx2dEffect.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/particleMgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiP2Title.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiP2TitleUnit.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiUtility.o\
	$(BUILD_DIR)/src/plugProjectEbisawaU/ebiP2TitleCamera.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiP2TitleLight.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenMemoryCard.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efxTPkEffectMgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efxEnemyGeneral.o\
	$(BUILD_DIR)/src/plugProjectEbisawaU/ebi3DGraph.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiGeometry.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebi2DGraph.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenOption.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenProgre.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiOptionMgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebi2DCallBack.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiCardMgr.o\
	$(BUILD_DIR)/src/plugProjectEbisawaU/ebiScreenFramework.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenPushStart.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenFileSelect.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenTitleMenu.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiSaveMgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenSaveMenu.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenFileSelect_Mgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiFileSelectMgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiCardMgr_Load.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiP2TitleCoordMgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiP2TitlePikmin.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiP2TitleKogane.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiP2TitleChappy.o\
	$(BUILD_DIR)/src/plugProjectEbisawaU/ebiScreenTMBack.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiMainTitleMgr.o\
	$(BUILD_DIR)/src/plugProjectEbisawaU/ebiP2TitleFog.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/efxEnemyBoss.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiCardEReader.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenOmake.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiOmakeMgr.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenOmakeCardE.o\
	$(BUILD_DIR)/asm/plugProjectEbisawaU/ebiScreenOmakeGame.o\
	$(BUILD_DIR)/src/plugProjectEbisawaU/ebiScreenInfoWindow.o\

KONO:=\
	$(BUILD_DIR)/asm/plugProjectKonoU/khWorldMap.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khCaveResult.o\
	$(BUILD_DIR)/src/plugProjectKonoU/khSceneLoader.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/newGame2DMgr.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/newScreenMgr.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khReadyGo.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khFinalFloor.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khDayEndResult.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khUtil.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khFinalResult.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khPayDept.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khWinLose.o\
	$(BUILD_DIR)/asm/plugProjectKonoU/khWinLoseReason.o\
	$(BUILD_DIR)/src/plugProjectKonoU/khMailSaveData.o\

BOOTUP:=\
	$(BUILD_DIR)/src/sysBootupU/sysBootup.o\

COMMON:=\
	$(BUILD_DIR)/src/sysCommonU/node.o\
	$(BUILD_DIR)/asm/sysCommonU/sysMath.o\
	$(BUILD_DIR)/src/sysCommonU/id32.o\
	$(BUILD_DIR)/src/sysCommonU/parameters.o\
	$(BUILD_DIR)/src/sysCommonU/stream.o\
	$(BUILD_DIR)/asm/sysCommonU/geometry.o\
	$(BUILD_DIR)/src/sysCommonU/mapCollision.o\
	$(BUILD_DIR)/asm/sysCommonU/camera.o\
	$(BUILD_DIR)/src/sysCommonU/tagparams.o\
	$(BUILD_DIR)/src/sysCommonU/sysTemplates.o\
	$(BUILD_DIR)/src/sysCommonU/mapCode.o\
	$(BUILD_DIR)/asm/sysCommonU/geomIntersection.o\
	$(BUILD_DIR)/asm/sysCommonU/geomOBBTree.o\
	$(BUILD_DIR)/asm/sysCommonU/geomTraceMove.o\
	$(BUILD_DIR)/asm/sysCommonU/geomCylinder.o\
	$(BUILD_DIR)/src/sysCommonU/geomClone.o\

GC:=\
	$(BUILD_DIR)/asm/sysGCU/system.o\
	$(BUILD_DIR)/asm/sysGCU/section.o\
	$(BUILD_DIR)/asm/sysGCU/gameflow.o\
	$(BUILD_DIR)/src/sysGCU/menuSection.o\
	$(BUILD_DIR)/asm/sysGCU/dvdThread.o\
	$(BUILD_DIR)/src/sysGCU/appThread.o\
	$(BUILD_DIR)/src/sysGCU/controller.o\
	$(BUILD_DIR)/asm/sysGCU/graphics.o\
	$(BUILD_DIR)/asm/sysGCU/matMath.o\
	$(BUILD_DIR)/asm/sysGCU/sysShape.o\
	$(BUILD_DIR)/asm/sysGCU/reset.o\
	$(BUILD_DIR)/src/sysGCU/dvdStatus.o\
	$(BUILD_DIR)/src/sysGCU/sysTimers.o\
	$(BUILD_DIR)/src/sysGCU/modelMgr.o\
	$(BUILD_DIR)/asm/sysGCU/heapStatus.o\
	$(BUILD_DIR)/asm/sysGCU/light.o\
	$(BUILD_DIR)/asm/sysGCU/wipe.o\
	$(BUILD_DIR)/asm/sysGCU/moviePlayer.o\
	$(BUILD_DIR)/asm/sysGCU/JSTObjectActor.o\
	$(BUILD_DIR)/asm/sysGCU/JSTObjectCamera.o\
	$(BUILD_DIR)/asm/sysGCU/JSTObjectGameActor.o\
	$(BUILD_DIR)/asm/sysGCU/JSTObjectSystem.o\
	$(BUILD_DIR)/src/sysGCU/JSTFindCreature.o\
	$(BUILD_DIR)/asm/sysGCU/movieConfig.o\
	$(BUILD_DIR)/src/sysGCU/gameConfig.o\
	$(BUILD_DIR)/src/sysGCU/fogMgr.o\
	$(BUILD_DIR)/asm/sysGCU/aramMgr.o\
	$(BUILD_DIR)/asm/sysGCU/resourceMgr.o\
	$(BUILD_DIR)/src/sysGCU/resourceMgr2D.o\
	$(BUILD_DIR)/asm/sysGCU/sysMaterialAnim.o\
	$(BUILD_DIR)/asm/sysGCU/P2DScreen.o\
	$(BUILD_DIR)/asm/sysGCU/movieMessage.o\
	$(BUILD_DIR)/asm/sysGCU/moviePlayerPauseAndDraw.o\
	$(BUILD_DIR)/asm/sysGCU/JSTObjectSpecialActor.o\
	$(BUILD_DIR)/src/sysGCU/messageSequence.o\
	$(BUILD_DIR)/asm/sysGCU/messageMgr.o\
	$(BUILD_DIR)/asm/sysGCU/messageObj.o\
	$(BUILD_DIR)/asm/sysGCU/messageRendering.o\
	$(BUILD_DIR)/src/sysGCU/message.o\
	$(BUILD_DIR)/asm/sysGCU/modelEffect.o\
	$(BUILD_DIR)/src/sysGCU/messageReference.o\
	$(BUILD_DIR)/src/sysGCU/simpleMessage.o\
	$(BUILD_DIR)/src/sysGCU/sysShapeAnimation.o\
	$(BUILD_DIR)/asm/sysGCU/sysShapeModel.o\
	$(BUILD_DIR)/asm/sysGCU/windowMessage.o\
	$(BUILD_DIR)/asm/sysGCU/memoryCard.o\
	$(BUILD_DIR)/asm/sysGCU/pikmin2MemoryCardMgr.o\
	$(BUILD_DIR)/asm/sysGCU/commonSaveData.o\
	$(BUILD_DIR)/asm/sysGCU/bootSection.o\
	$(BUILD_DIR)/asm/sysGCU/titleSection.o\
	$(BUILD_DIR)/asm/sysGCU/loadResource.o\
	$(BUILD_DIR)/src/sysGCU/rootMenuSection.o\
	$(BUILD_DIR)/asm/sysGCU/demoSection.o\
	$(BUILD_DIR)/asm/sysGCU/THPAudioDecode.o\
	$(BUILD_DIR)/src/sysGCU/THPDraw.o\
	$(BUILD_DIR)/asm/sysGCU/THPPlayer.o\
	$(BUILD_DIR)/asm/sysGCU/THPRead.o\
	$(BUILD_DIR)/asm/sysGCU/THPVideoDecode.o\
	$(BUILD_DIR)/asm/sysGCU/pikmin2THPPlayer.o\
	$(BUILD_DIR)/asm/sysGCU/captionMgr.o\
	$(BUILD_DIR)/asm/sysGCU/captionMessage.o\
	$(BUILD_DIR)/asm/sysGCU/screenScene.o\
	$(BUILD_DIR)/asm/sysGCU/screenMgr.o\
	$(BUILD_DIR)/asm/sysGCU/screenObj.o\
	$(BUILD_DIR)/asm/sysGCU/JSTObjectParticleActor.o\
	$(BUILD_DIR)/asm/sysGCU/moviePlayerAudio.o\
	$(BUILD_DIR)/asm/sysGCU/illustratedBookMessage.o\
	$(BUILD_DIR)/src/sysGCU/sysDrawBuffer.o\
	$(BUILD_DIR)/src/sysGCU/dvdErrorMessage.o\
	$(BUILD_DIR)/asm/sysGCU/pikmin2AramMgr.o\
	$(BUILD_DIR)/src/sysGCU/messageAnalyzer.o\

UTILITY:=\
	$(BUILD_DIR)/asm/utilityU/menu.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_Director.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_Factory.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_ObjSound.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_Demo.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_Scene.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_BossMgr.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_Se.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_DirectorMgr.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_Sound.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_TrackMap.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_CreaturePrm.o\
	$(BUILD_DIR)/asm/utilityU/PSMainSide_ObjCalc.o\
