// code autogenerated from ghidra
#include "dolphin.h"


/*
 * --INFO--
 * Address:	800C15F0
 * Size:	0000C8
 */
// void __va_arg(void)
int * __va_arg(char *param_1,int param_2)
{
  int iVar1;
  uint uVar2;
  char *pcVar3;
  int **ppiVar4;
  uint uVar5;
  char cVar6;
  int iVar7;
  char cVar8;
  int iVar9;
  int iVar10;
  cVar6 = *param_1;
  iVar1 = 8;
  iVar7 = 4;
  cVar8 = '\x01';
  uVar2 = 0;
  iVar9 = 0;
  iVar10 = 4;
  pcVar3 = param_1;
  if (param_2 == 3) {
    cVar6 = param_1[1];
    pcVar3 = param_1 + 1;
    iVar7 = 8;
    iVar9 = 0x20;
    iVar10 = 8;
  }
  uVar5 = (int)(cVar6); // doesn't match.
  if (param_2 == 2) {
    iVar7 = 8;
    iVar1 = 7;
    uVar2 = (uint)((uVar5 & 1) != 0);
    cVar8 = '\x02';
  }
  if ((int)uVar5 < iVar1) {
    iVar1 = *(int *)(param_1 + 8);
    *pcVar3 = (char)(uVar5 + uVar2) + cVar8;
    ppiVar4 = (int **)(iVar1 + iVar9 + (uVar5 + uVar2) * iVar10);
  }
  else {
    *pcVar3 = '\b';
    ppiVar4 = (int **)(~(iVar7 - 1U) & (iVar7 + *(int *)(param_1 + 4)) - 1U);
    *(int *)(param_1 + 4) = (int)ppiVar4 + iVar7;
  }
  if (param_2 == 0) {
    ppiVar4 = (int **)*ppiVar4;
  }
  return (int *)ppiVar4;
/*
.loc_0x0:
  lbz       r7, 0x0(r3)
  cmpwi     r4, 0x3
  mr        r6, r3
  li        r0, 0x8
  li        r8, 0x4
  extsb     r7, r7
  li        r9, 0x1
  li        r5, 0
  li        r10, 0
  li        r11, 0x4
  bne-      .loc_0x44
  lbz       r7, 0x1(r3)
  addi      r6, r3, 0x1
  li        r8, 0x8
  li        r10, 0x20
  extsb     r7, r7
  li        r11, 0x8

.loc_0x44:
  cmpwi     r4, 0x2
  bne-      .loc_0x64
  rlwinm.   r0,r7,0,31,31
  li        r8, 0x8
  li        r0, 0x7
  beq-      .loc_0x60
  li        r5, 0x1

.loc_0x60:
  li        r9, 0x2

.loc_0x64:
  cmpw      r7, r0
  bge-      .loc_0x8C
  add       r7, r7, r5
  lwz       r5, 0x8(r3)
  mullw     r3, r7, r11
  add       r0, r7, r9
  stb       r0, 0x0(r6)
  add       r6, r10, r3
  add       r6, r5, r6
  b         .loc_0xB4

.loc_0x8C:
  li        r5, 0x8
  subi      r0, r8, 0x1
  stb       r5, 0x0(r6)
  not       r6, r0
  lwz       r0, 0x4(r3)
  add       r5, r8, r0
  subi      r0, r5, 0x1
  and       r6, r6, r0
  add       r0, r6, r8
  stw       r0, 0x4(r3)

.loc_0xB4:
  cmpwi     r4, 0
  bne-      .loc_0xC0
  lwz       r6, 0x0(r6)

.loc_0xC0:
  mr        r3, r6
  blr
*/
}